import { Component, OnInit } from '@angular/core';
import { IonApp, IonRouterOutlet, Platform } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { QuillFloatingToolbarComponent } from './rich-text-editor/components/quill-floating-toolbar.component';
import { SplashScreen } from '@capacitor/splash-screen';
import { StatusBar, Style } from '@capacitor/status-bar';

import {
  addCircleOutline,
  addOutline,
  arrowBack,
  arrowBackOutline,
  attachOutline,
  bodyOutline,
  bookmarksOutline,
  bookOutline,
  bug,
  bugOutline,
  buildOutline,
  calendarOutline,
  cameraOutline,
  callOutline,
  chatboxEllipsesOutline,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  chevronBack,
  chevronBackCircleOutline,
  chevronBackOutline,
  chevronDown,
  chevronDownOutline,
  chevronForward,
  chevronForwardCircleOutline,
  chevronForwardOutline,
  chatbubbleOutline,
  closeCircle,
  closeCircleOutline,
  closeOutline,
  cloudOutline,
  cloudDownloadOutline,
  construct,
  constructOutline,
  createOutline,
  documentOutline,
  documentTextOutline,
  eyeOffOutline,
  eyeOutline,
  fishOutline,
  fitness,
  fitnessOutline,
  flame,
  flashOutline,
  flowerOutline,
  folderOutline,
  footsteps,
  footstepsOutline,
  globeOutline,
  heartOutline,
  helpBuoy,
  helpBuoyOutline,
  helpCircleOutline,
  home,
  homeOutline,
  imageOutline,
  imagesOutline,
  information,
  journalOutline,
  keyOutline,
  layersOutline,
  leafOutline,
  libraryOutline,
  linkOutline,
  list,
  listCircleOutline,
  listOutline,
  lockClosedOutline,
  logoAndroid,
  logoApple,
  logoYoutube,
  mailOutline,
  micOutline,
  moonOutline,
  musicalNoteOutline,
  musicalNotesOutline,
  notificationsOutline,
  pauseCircleOutline,
  people,
  peopleOutline,
  phonePortraitOutline,
  pieChartOutline,
  playCircleOutline,
  rainyOutline,
  refresh,
  refreshCircle,
  ribbon,
  ribbonOutline,
  sadOutline,
  saveOutline,
  search,
  send,
  settingsOutline,
  shareOutline,
  shieldOutline,
  shieldCheckmarkOutline,
  snowOutline,
  sparklesOutline,
  starOutline,
  stopCircle,
  stopCircleOutline,
  sunnyOutline,
  textOutline,
  timeOutline,
  trashOutline,
  trophyOutline,
  waterOutline,
  colorPaletteOutline,
  happyOutline,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  imports: [IonApp, IonRouterOutlet, QuillFloatingToolbarComponent],
})
export class AppComponent implements OnInit {
  constructor(private platform: Platform) {}

  ngOnInit() {
    this.initializeApp();
    
    // Register all Ionic icons globally
    addIcons({
      addCircleOutline,
      addOutline,
      arrowBack,
      arrowBackOutline,
      attachOutline,
      bodyOutline,
      bookmarksOutline,
      bookOutline,
      bug,
      bugOutline,
      buildOutline,
      calendarOutline,
      cameraOutline,
      callOutline,
      chatbubbleOutline,
      chatboxEllipsesOutline,
      checkmark,
      checkmarkCircle,
      checkmarkCircleOutline,
      chevronBack,
      chevronBackCircleOutline,
      chevronBackOutline,
      chevronDown,
      chevronDownOutline,
      chevronForward,
      chevronForwardCircleOutline,
      chevronForwardOutline,
      closeCircle,
      closeCircleOutline,
      closeOutline,
      cloudOutline,
      cloudDownloadOutline,
      construct,
      constructOutline,
      createOutline,
      documentOutline,
      documentTextOutline,
      eyeOffOutline,
      eyeOutline,
      fishOutline,
      fitness,
      fitnessOutline,
      flame,
      flashOutline,
      flowerOutline,
      folderOutline,
      footsteps,
      footstepsOutline,
      globeOutline,
      heartOutline,
      helpBuoy,
      helpBuoyOutline,
      helpCircleOutline,
      home,
      homeOutline,
      imageOutline,
      imagesOutline,
      information,
      journalOutline,
      keyOutline,
      layersOutline,
      leafOutline,
      libraryOutline,
      linkOutline,
      list,
      listCircleOutline,
      listOutline,
      lockClosedOutline,
      logoAndroid,
      logoApple,
      logoYoutube,
      mailOutline,
      micOutline,
      moonOutline,
      musicalNoteOutline,
      musicalNotesOutline,
      notificationsOutline,
      pauseCircleOutline,
      people,
      peopleOutline,
      phonePortraitOutline,
      pieChartOutline,
      playCircleOutline,
      rainyOutline,
      refresh,
      refreshCircle,
      ribbon,
      ribbonOutline,
      sadOutline,
      saveOutline,
      search,
      send,
      settingsOutline,
      shareOutline,
      shieldOutline,
      shieldCheckmarkOutline,
      snowOutline,
      sparklesOutline,
      starOutline,
      stopCircle,
      stopCircleOutline,
      sunnyOutline,
      textOutline,
      timeOutline,
      trashOutline,
      trophyOutline,
      waterOutline,
      colorPaletteOutline,
      happyOutline,
      // Custom icons
      'logo-spotify': './assets/custom-icons/logo-spotify.svg',
      'bar-chart1': './assets/custom-icons/bar-chart1.svg',
      'donut-chart1': './assets/custom-icons/donut-chart1.svg',
      'list1': './assets/custom-icons/list1.svg',
      'editor-ol': './assets/custom-icons/editor-ol.svg',
      'award': './assets/custom-icons/award.svg',
    });
  }

  async initializeApp() {
    await this.platform.ready();
    
    if (this.platform.is('capacitor')) {
      // Hide the splash screen after the app is ready
      await SplashScreen.hide();
      
      // Configure the status bar
      await StatusBar.setStyle({ style: Style.Light });
      await StatusBar.setBackgroundColor({ color: '#ffffff' });
    }
  }
}
